In [1]:
import torch

# Example
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->ji', [a])

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [2]:
#Q5.1
q1a = torch.randn(3,2,5)
q1b = torch.randn(3)
torch.einsum('ijk,i->jk',[q1a,q1b])

tensor([[-1.2061, -1.1289,  3.2449,  2.0738, -0.5003],
        [-1.0436, -0.5560, -0.4786,  2.1590, -2.8435]])

In [3]:
#Q5.2
q2 = torch.randn(3,2,5,3)
torch.einsum('ijkl->ik',[q2])

tensor([[-6.7280, -0.6500, -0.7285,  2.2631, -1.4154],
        [ 2.4351,  1.3366, -4.5421, -0.2333,  4.3568],
        [ 1.2702,  1.9210,  0.1328, -1.2590,  0.4741]])

In [4]:
#Q5.3
q3 = torch.randn(3,2,5,3)
torch.einsum('ijkl->ki',[q3])

tensor([[ 0.0547,  3.6758, -0.9661],
        [-2.4279,  0.6336, -5.0624],
        [-4.4450,  0.0596,  1.5150],
        [ 2.8499,  1.4035,  1.6870],
        [-2.2888, -0.8119, -4.2149]])

In [5]:
#Q5.4
q4 = torch.randn(3,2,5)
torch.einsum('ijk,ijk->i',[q4,q4])

tensor([19.4891, 15.3892,  7.2393])

In [7]:
#Q5.5
q5a = torch.arange(6).reshape(2, 3)
q5g = torch.arange(6).reshape(2, 3)
q5gt = q5g.t()
q5b = torch.arange(6).reshape(2, 3)
torch.einsum('de,ef,fl->dl',[q5a,q5gt,q5b])

tensor([[ 42,  61,  80],
        [150, 214, 278]])